# Generated by Django 2.1.5 on 2019-02-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
