# Generated by Django 2.1.5 on 2019-03-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190215_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created',), 'verbose_name': '用户关系', 'verbose_name_plural': '用户关系'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
