# Generated by Django 2.1.5 on 2019-02-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweibo', '0004_msginfo_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('click_count', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweibo.MsgInfo')),
            ],
        ),
    ]
