# Generated by Django 2.1.5 on 2019-03-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweibo', '0005_hotmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': '公告',
            },
        ),
        migrations.AlterModelOptions(
            name='hotmsg',
            options={'verbose_name': '热门微博', 'verbose_name_plural': '热门微博'},
        ),
        migrations.AlterModelOptions(
            name='msginfo',
            options={'verbose_name': '微博消息', 'verbose_name_plural': '微博消息'},
        ),
        migrations.AlterModelOptions(
            name='usermsgindex',
            options={'verbose_name': '用户消息索引', 'verbose_name_plural': '用户消息索引'},
        ),
    ]
